export default {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOADING: 'LOADING',
    GET_FRIENDS: 'GET_FRIENDS',
    ADD_FRIENDS: 'ADD_FRIENDS',
    DELETE_FRIENDS: 'DELETE_FRIENDS',
    LIKE_FRIEND: 'LIKED_FRIEND',
    ERROR: 'ERROR'
};